import jsPDF from "jspdf";

export interface BriefPDFParams {
  brandName: string;
  productName: string;
  campaignGoal: string;
  copy: {
    headline: string;
    primaryText: string;
    description: string;
    cta: string;
    copywriterNote: string;
  };
  targeting: {
    locations?: { name: string; source: string }[];
    age_min?: number;
    age_max?: number;
    gender?: string;
    interests?: string[];
    behaviours?: string[];
    age_reasoning?: string;
    interest_reasoning?: string;
  };
  budget: {
    recommended_daily_ngn?: number;
    recommended_duration_days?: number;
    reasoning?: string;
  };
  timing: {
    peak_days?: string[];
    launch_recommendation?: string;
  };
  warnings: string[];
  generatedAt: string;
}

export function generateBriefPDF(params: BriefPDFParams): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // ── Helpers ──────────────────────────────────────────────────────────────

  const addLine = (text: string, size = 11, bold = false) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, pageWidth - 40);
    doc.text(lines, 20, y);
    y += lines.length * (size * 0.4) + 4;
  };

  const addSection = (title: string) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    y += 4;
    doc.setFillColor(30, 30, 40);
    doc.rect(15, y - 5, pageWidth - 30, 10, "F");
    doc.setTextColor(150, 130, 255);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text(title.toUpperCase(), 20, y + 2);
    doc.setTextColor(0, 0, 0);
    y += 10;
  };

  // ── Header ────────────────────────────────────────────────────────────────

  doc.setFillColor(15, 15, 25);
  doc.rect(0, 0, pageWidth, 35, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("CAMPAIGN BRIEF", 20, 18);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by Omni-target · ${params.generatedAt}`, 20, 27);
  doc.setTextColor(0, 0, 0);
  y = 45;

  // ── Product Info ──────────────────────────────────────────────────────────

  addLine(`${params.brandName} — ${params.productName}`, 14, true);
  addLine(`Campaign Goal: ${params.campaignGoal}`);
  y += 4;

  // ── Ad Copy ───────────────────────────────────────────────────────────────

  addSection("Ad Copy");
  addLine("HEADLINE", 9, true);
  addLine(params.copy.headline, 12);
  y += 2;
  addLine("PRIMARY TEXT", 9, true);
  addLine(params.copy.primaryText);
  y += 2;
  addLine("LINK DESCRIPTION", 9, true);
  addLine(params.copy.description);
  y += 2;
  addLine("CTA BUTTON", 9, true);
  addLine(params.copy.cta);
  y += 2;
  addLine("COPYWRITER'S NOTE", 9, true);
  addLine(params.copy.copywriterNote, 10);

  // ── Targeting ─────────────────────────────────────────────────────────────

  addSection("Targeting Settings");

  const locations = params.targeting.locations ?? [];
  addLine("LOCATIONS", 9, true);
  if (locations.length > 0) {
    locations.forEach((loc) => {
      addLine(
        `• ${loc.name} (${loc.source === "from_data" ? "from your orders" : "recommended"})`,
        10
      );
    });
  } else {
    addLine("• Set manually in Meta Ads Manager", 10);
  }
  y += 2;

  const ageMin = params.targeting.age_min ?? 0;
  const ageMax = params.targeting.age_max ?? 0;
  addLine("AGE RANGE", 9, true);
  if (ageMin > 0 && ageMax > 0) {
    addLine(`${ageMin} — ${ageMax} years`);
    if (params.targeting.age_reasoning) {
      addLine(params.targeting.age_reasoning, 9);
    }
  } else {
    addLine("Check Meta audience insights for your category", 10);
  }
  y += 2;

  addLine("GENDER", 9, true);
  const gender = params.targeting.gender ?? "all";
  addLine(
    gender === "all" ? "All genders" : gender === "female" ? "Women only" : "Men only"
  );
  y += 2;

  const interests = params.targeting.interests ?? [];
  addLine("INTERESTS TO ADD IN META", 9, true);
  if (interests.length > 0) {
    interests.forEach((i) => addLine(`• ${i}`, 10));
  } else {
    addLine("• No interests available — add manually", 10);
  }
  y += 2;

  const behaviours = params.targeting.behaviours ?? [];
  addLine("BEHAVIOURS TO ADD", 9, true);
  if (behaviours.length > 0) {
    behaviours.forEach((b) => addLine(`• ${b}`, 10));
  } else {
    addLine("• Engaged Shoppers", 10);
    addLine("• Online shoppers", 10);
  }

  // ── Budget ────────────────────────────────────────────────────────────────

  addSection("Budget Recommendation");
  const daily = params.budget.recommended_daily_ngn;
  const duration = params.budget.recommended_duration_days;
  if (daily) {
    addLine(`Daily Budget: \u20a6${daily.toLocaleString()}`, 12, true);
  } else {
    addLine("Daily Budget: Set in Meta Ads Manager (₦5,000/day recommended)", 12, true);
  }
  if (duration) {
    addLine(`Duration: ${duration} days`);
  }
  if (params.budget.reasoning) {
    addLine(params.budget.reasoning, 10);
  }

  // ── Timing ────────────────────────────────────────────────────────────────

  addSection("When to Launch");
  if (params.timing.launch_recommendation) {
    addLine(params.timing.launch_recommendation);
  }
  const peakDays = params.timing.peak_days ?? [];
  if (peakDays.length > 0) {
    addLine(`Peak days: ${peakDays.join(", ")}`, 10);
  }

  // ── Warnings ──────────────────────────────────────────────────────────────

  if (params.warnings.length > 0) {
    addSection("Before You Launch");
    params.warnings.forEach((w) => addLine(`\u26a0 ${w}`, 10));
  }

  // ── Footer on every page ──────────────────────────────────────────────────

  const pageCount = (doc.internal as any).pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Omni-target Campaign Brief · Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // ── Save ──────────────────────────────────────────────────────────────────

  doc.save(
    `omni-target-brief-${params.productName.replace(/\s+/g, "-").toLowerCase()}.pdf`
  );
}
