# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c6afe04bdb857fd30f081fd555feb6b"
name = "Omni Target"
application_url = "https://app.omnitarget.co"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri               = "/api/webhooks/privacy"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_inventory,read_orders,read_product_listings,read_products,read_reports"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://app.omnitarget.co/api/auth/shopify/callback" ]

[pos]
embedded = false
